# Container image that runs your code
FROM ghcr.io/courtois-neuromod/datalad:main

ADD . /actions
WORKDIR /work
RUN source /opt/venv/bin/activate && python -m pip install --no-cache-dir pytest-order

ENTRYPOINT ["pytest", "-s", "--log-cli-level", "WARN", "/actions/tests"]
